language: scala
jdk: oraclejdk8
scala: 2.12.3

before_script: cd rosette-scala

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"

script:
   - sbt ++$TRAVIS_SCALA_VERSION test compile assembly

notifications:
  email:
    on_success: never

deploy:
  provider: releases
  file: "target/scala-2.12/rosette.jar"
  skip_cleanup: true
  api_key:
    secure: EYxLTLp4M6K4ykeXYTnKeZp/6Hm5ZMKhPywSyV9rFz2+x6WbuWj2nb9V7FsRQn8h8lu5oLNix525ccBtIS2YrKsiwK5vl5E4ofhq6+KyYXQAYbRyPm+OTBrnQACxFH5iZzX3CzJdYbo3I4dTcGLQ9sh51Dp0TG5O34jhbSw1G662l7cLlw6vKNTiBhJbLz8G/fQaB+3Z2CEcJphDQQcVIOKG4YU3d5amofUCJFSmZbqJchpiXep+i6kdUrsTWCzY78HEQWbC1R11QkJSmkIDh8tX/K/hpv0zmtCO+O+hg3/p/xibCSfKX3qfw4OKIcgQlG/5n4Qc5ntP4w4kUUOp0F7qK0CGn6ipYuoMwtYfCtX3Lz12FyJpP8ayHHd2cKE1VQVBHWCTroVxc+vb0ZDbYANilJm/xo1h0xVZL0md0KsjnpSGVDSk9vjHvn5N1uXjjYd7vC5wFY5sCS1aceyZHGrowXIDpfJL/grWySvMESMpTx2VfGR2NsBwJen6i8PbLO5BEHCx9EXxl6tfsDUYuQSQ4od8exSiCdXrtnEqe74pFYAA4eCIaViXCji5J8b82B4KGHKSupgCumQSnL3tECII4kjIkh+YCq3ZvBabWFZfp4DdfeKHP+n2FcJgELfR4HnNa9BCc3UeAcBW9pEFKL8/Y2MEqPHsoJUW8JjgNxw=
  on:
    tags: true
